name: Build AutoLibrarian

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21 for Gradle
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.12'

      - name: Build the Mod
        run: gradle build

      - name: Upload JAR Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AutoLibrarian-Build
          path: build/libs/*.jar
